version: "3.3"
services:
  monitor:
    image: blockchainit/source-verify-monitor:${TAG}
    env_file:
    - .env.prod
    container_name: monitor
    ports:
    - "${MONITOR_EXTERNAL_PORT}:${MONITOR_PORT}"
    networks:
    - source-verify-network
    volumes:
    - ./repository:/app/repository
    restart: always
  ui:
    image: blockchainit/source-verify-ui:${TAG}
    env_file:
    - .env.prod
    container_name: ui
    ports:
    - "${UI_EXTERNAL_PORT}:${UI_PORT}"
    networks:
    - source-verify-network
    restart: always
  server:
    image: blockchainit/source-verify-server:${TAG}
    env_file:
    - .env.prod
    container_name: server
    ports:
    - "${SERVER_EXTERNAL_PORT}:${SERVER_PORT}"
    networks:
    - source-verify-network
    volumes:
    - ./repository:/app/repository
    restart: always
  repository:
    image: blockchainit/source-verify-repository:${TAG}
    restart: always
    container_name: repository
    volumes:
      - h5ai:/h5ai
      - ./repository:/data
      - ./h5ai-nginx/options.json:/h5ai/_h5ai/private/conf/options.json
      - ./h5ai-nginx/types.json:/h5ai/_h5ai/private/conf/types.json
    ports:
    - ${NGINX_EXTERNAL_PORT}:${NGINX_PORT}
networks:
  source-verify-network:
volumes:
  repository:
  db:
  h5ai:
    driver: local
 
