openapi: "3.0.0"
info:
  version: 1.0.0
  title: Sourcify API
  description: API to interact with Sourcify
  license:
    name: MIT
    url: https://github.com/ethereum/sourcify/blob/master/LICENSE
servers:
  - url: https://sourcify.dev/server
    description: Production server 
  - url: https://staging.sourcify.dev/server
    description: Staging server 
  - url: http://localhost:5555
    description: Local development server address on default port 5555.
paths:
  /session/data:
    $ref: "src/server/controllers/verification/session-state/data.session-state.paths.yaml#/paths/~1session~1data"
  /session/clear:
    $ref: "src/server/controllers/verification/session-state/clear.session-state.paths.yaml#/paths/~1session~1clear"
  /session/input-files:
    $ref: "src/server/controllers/verification/session-state/input-files.session-state.paths.yaml#/paths/~1session~1input-files"
  /session/input-contract:
    $ref: "src/server/controllers/verification/session-state/input-contract.session-state.paths.yaml#/paths/~1session~1input-contract"
  /verify:
    $ref: "src/server/controllers/verification/verify/stateless/verify.stateless.paths.yaml#/paths/~1verify"
  /session/verify-checked:
    $ref: "src/server/controllers/verification/verify/session/verify.session.paths.yaml#/paths/~1session~1verify-checked"
  /verify/solc-json:
    $ref: "src/server/controllers/verification/solc-json/stateless/solc-json.stateless.paths.yaml#/paths/~1verify~1solc-json"
  /session/input-solc-json:
    $ref: "src/server/controllers/verification/solc-json/session/solc-json.session.paths.yaml#/paths/~1session~1input-solc-json"
  /verify/create2:
    $ref: "src/server/controllers/verification/create2/stateless/create2.stateless.paths.yaml#/paths/~1verify~1create2"
  /session/verify/create2:
    $ref: "src/server/controllers/verification/create2/session/create2.session.paths.yaml#/paths/~1session~1verify~1create2"
  /session/verify/create2/compile:
    $ref: "src/server/controllers/verification/create2/session/compile.create2.session.paths.yaml#/paths/~1session~1verify~1create2~1compile"
  /verify/etherscan:
    $ref: "src/server/controllers/verification/etherscan/stateless/etherscan.stateless.paths.yaml#/paths/~1verify~1etherscan"
  /session/verify/etherscan:
    $ref: "src/server/controllers/verification/etherscan/session/etherscan.session.paths.yaml#/paths/~1session~1verify~1etherscan"
  /check-all-by-addresses:
    $ref: "src/server/controllers/repository/check-all-by-addresses.stateless.paths.yaml#/paths/~1check-all-by-addresses"
  /check-by-addresses:
    $ref: "src/server/controllers/repository/check-by-addresses.stateless.paths.yaml#/paths/~1check-by-addresses"
  /files/contracts/{chain}:
    $ref: "src/server/controllers/repository/get-contract-addresses-all.stateless.paths.yaml#/paths/~1files~1contracts~1{chain}"
  /contracts/{full_match | partial_match}/{chain}/{address}/{filePath}:
    $ref: "src/server/controllers/repository/get-file-static.stateless.paths.yaml#/paths/~1contracts~1{full_match | partial_match}~1{chain}~1{address}~1{filePath}"
  /files/tree/any/{chain}/{address}:
    $ref: "src/server/controllers/repository/get-file-tree-all.stateless.paths.yaml#/paths/~1files~1tree~1any~1{chain}~1{address}"
  /files/tree/{chain}/{address}:
    $ref: "src/server/controllers/repository/get-file-tree-full.stateless.paths.yaml#/paths/~1files~1tree~1{chain}~1{address}"
  /files/any/{chain}/{address}:
    $ref: "src/server/controllers/repository/get-source-files-all.stateless.paths.yaml#/paths/~1files~1any~1{chain}~1{address}"
  /files/{chain}/{address}:
    $ref: "src/server/controllers/repository/get-source-files-full.stateless.paths.yaml#/paths/~1files~1{chain}~1{address}"
